### ISSUE TITLE
number labels

### ISSUE THREAD

**Issue by jcavalieri** [toretore/barby#50] opened 2015-06-25 17:30 UTC
Hi toretore, and barby contributors,

Would I be able to generate a barcode like the following attached image.
![screen shot 2015-06-25 at 11 34 47 am](https://cloud.githubusercontent.com/assets/2171614/8360962/bbcd7772-1b35-11e5-857d-c1d6e8786b06.png)

I see that ean13 with a 5 supplemental is possible. However I don't see a way to include the decimal digits. E.g. under the 13 and above the 5 in the image.

Thanks,
John

**Comment by toretore** [comment] 2015-06-25 19:08
Duplicate of #12, #36, #45.

**Closed by toretore** 2015-06-25 19:08 UTC

**Comment by jcavalieri** [comment] 2015-06-25 19:25
doh, should have searched past issues, my bad, thanks for the quick response
